// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function PickExportSavePath(arg1:string,arg2:string):Promise<string>;

export function PickReviewPackSavePath(arg1:string):Promise<string>;

export function PickWorkbook():Promise<string>;

export function RenderReviewPack(arg1:string):Promise<string>;

export function SaveExport(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<void>;

export function SaveReviewPack(arg1:string,arg2:string):Promise<void>;

export function ScanWorkbook(arg1:string):Promise<model.AuditReport>;
