// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function PickExportSavePath(arg1, arg2) {
  return window['go']['main']['AuditService']['PickExportSavePath'](arg1, arg2);
}

export function PickReviewPackSavePath(arg1) {
  return window['go']['main']['AuditService']['PickReviewPackSavePath'](arg1);
}

export function PickWorkbook() {
  return window['go']['main']['AuditService']['PickWorkbook']();
}

export function RenderReviewPack(arg1) {
  return window['go']['main']['AuditService']['RenderReviewPack'](arg1);
}

export function SaveExport(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['AuditService']['SaveExport'](arg1, arg2, arg3, arg4, arg5);
}

export function SaveReviewPack(arg1, arg2) {
  return window['go']['main']['AuditService']['SaveReviewPack'](arg1, arg2);
}

export function ScanWorkbook(arg1) {
  return window['go']['main']['AuditService']['ScanWorkbook'](arg1);
}
