// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function BuildAIHandoff(arg1:string,arg2:model.PromptBundleOptions):Promise<model.AIHandoffPayload>;

export function BuildEvidencePacket(arg1:string):Promise<model.EvidencePacketV1>;

export function BuildEvidencePacketJSON(arg1:string,arg2:model.PromptBundleOptions):Promise<string>;

export function BuildPromptBundle(arg1:string,arg2:model.PromptBundleOptions):Promise<model.PromptBundleV1>;

export function BuildPromptBundleJSON(arg1:string,arg2:model.PromptBundleOptions):Promise<string>;

export function PickExportSavePath(arg1:string,arg2:string):Promise<string>;

export function PickJSONSavePath(arg1:string):Promise<string>;

export function PickReviewPackSavePath(arg1:string):Promise<string>;

export function PickWorkbook():Promise<string>;

export function RenderReviewPack(arg1:string):Promise<string>;

export function SaveEvidencePacket(arg1:string,arg2:string,arg3:model.PromptBundleOptions):Promise<void>;

export function SaveExport(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>,arg6:boolean):Promise<void>;

export function SavePromptBundle(arg1:string,arg2:string,arg3:model.PromptBundleOptions):Promise<void>;

export function SaveReviewPack(arg1:string,arg2:string):Promise<void>;

export function SaveUnderstandingReport(arg1:string,arg2:string,arg3:string,arg4:model.PromptBundleOptions):Promise<void>;

export function ScanWorkbook(arg1:string):Promise<model.AuditReport>;

export function ValidateUnderstandingReport(arg1:string,arg2:string,arg3:model.PromptBundleOptions):Promise<model.UnderstandingValidationResult>;
