// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function BuildAIHandoff(arg1, arg2) {
  return window['go']['main']['AuditService']['BuildAIHandoff'](arg1, arg2);
}

export function BuildEvidencePacket(arg1) {
  return window['go']['main']['AuditService']['BuildEvidencePacket'](arg1);
}

export function BuildEvidencePacketJSON(arg1, arg2) {
  return window['go']['main']['AuditService']['BuildEvidencePacketJSON'](arg1, arg2);
}

export function BuildPromptBundle(arg1, arg2) {
  return window['go']['main']['AuditService']['BuildPromptBundle'](arg1, arg2);
}

export function BuildPromptBundleJSON(arg1, arg2) {
  return window['go']['main']['AuditService']['BuildPromptBundleJSON'](arg1, arg2);
}

export function PickExportSavePath(arg1, arg2) {
  return window['go']['main']['AuditService']['PickExportSavePath'](arg1, arg2);
}

export function PickJSONSavePath(arg1) {
  return window['go']['main']['AuditService']['PickJSONSavePath'](arg1);
}

export function PickReviewPackSavePath(arg1) {
  return window['go']['main']['AuditService']['PickReviewPackSavePath'](arg1);
}

export function PickWorkbook() {
  return window['go']['main']['AuditService']['PickWorkbook']();
}

export function RenderReviewPack(arg1) {
  return window['go']['main']['AuditService']['RenderReviewPack'](arg1);
}

export function SaveEvidencePacket(arg1, arg2, arg3) {
  return window['go']['main']['AuditService']['SaveEvidencePacket'](arg1, arg2, arg3);
}

export function SaveExport(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['AuditService']['SaveExport'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function SavePromptBundle(arg1, arg2, arg3) {
  return window['go']['main']['AuditService']['SavePromptBundle'](arg1, arg2, arg3);
}

export function SaveReviewPack(arg1, arg2) {
  return window['go']['main']['AuditService']['SaveReviewPack'](arg1, arg2);
}

export function SaveUnderstandingReport(arg1, arg2, arg3, arg4) {
  return window['go']['main']['AuditService']['SaveUnderstandingReport'](arg1, arg2, arg3, arg4);
}

export function ScanWorkbook(arg1) {
  return window['go']['main']['AuditService']['ScanWorkbook'](arg1);
}

export function ValidateUnderstandingReport(arg1, arg2, arg3) {
  return window['go']['main']['AuditService']['ValidateUnderstandingReport'](arg1, arg2, arg3);
}
